# Generated by Django 4.1.7 on 2023-02-23 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevUser',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=26)),
                ('UserEmail', models.EmailField(max_length=60)),
                ('UserPassword', models.CharField(max_length=16)),
                ('UserPoints', models.IntegerField(default=0)),
                ('UserRole', models.TextField(choices=[('Developer', 'DEV'), ('Senior', 'SEN'), ('Admin', 'ADM')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=30)),
                ('ProjectDescription', models.CharField(max_length=200)),
                ('ProjectStatus', models.CharField(choices=[('FI', 'Finished'), ('IP', 'InProgress'), ('CU', 'Coming Up')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TicketId', models.AutoField(primary_key=True, serialize=False)),
                ('TicketDescription', models.CharField(max_length=255)),
                ('TicketStatus', models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('CL', 'Closed')], max_length=20)),
                ('TicketPriority', models.CharField(choices=[('VH', 'Very Important'), ('H', 'Important'), ('M', 'Medium'), ('L', 'Low')], max_length=16)),
                ('TicketPoints', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('TicketProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tproject', to='BugTracker.project')),
                ('TicketSubmittedBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ticket_submitted_by', to='BugTracker.devuser')),
                ('ticketassignedto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignedto', to='BugTracker.devuser')),
            ],
        ),
        migrations.AddField(
            model_name='devuser',
            name='UserProject',
            field=models.ManyToManyField(blank=True, to='BugTracker.project'),
        ),
    ]
