# Generated by Django 4.1.7 on 2023-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketExected',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketObserved',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
