# Generated by Django 4.1.7 on 2023-04-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0002_ticket_ticketexected_ticket_ticketobserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='TicketExected',
            new_name='TicketExpected',
        ),
    ]
