# Generated by Django 4.1.7 on 2023-03-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BugTracker', '0002_alter_ticket_ticketassignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketAssignedTo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedto', to=settings.AUTH_USER_MODEL),
        ),
    ]
