# Generated by Django 4.1.7 on 2023-02-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0002_alter_ticket_ticketassignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketassignedto',
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketAssignedTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignedto', to='BugTracker.devuser'),
        ),
    ]
