# Generated by Django 4.1.7 on 2023-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0003_rename_ticketexected_ticket_ticketexpected'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='MonthlyPoints',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='devuser',
            name='last_reset',
            field=models.DateTimeField(null=True),
        ),
    ]
