# Generated by Django 4.1.7 on 2023-04-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0004_devuser_monthlypoints_devuser_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='devUserName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
