# Generated by Django 4.1.7 on 2023-04-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0005_devuser_devusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
