# Generated by Django 4.1.7 on 2023-04-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0007_alter_devuser_devusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='MonthlyPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devuser',
            name='UserPoints',
            field=models.IntegerField(default=0),
        ),
    ]
