# Generated by Django 4.1.7 on 2023-03-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0007_alter_ticket_ticketsubmittedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tproject', to='BugTracker.project'),
        ),
    ]
