# Generated by Django 4.1.7 on 2023-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0008_alter_devuser_monthlypoints_alter_devuser_userpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='devUserName',
            field=models.CharField(blank=True, default='Developer', max_length=20, null=True),
        ),
    ]
