# Generated by Django 4.1.7 on 2023-03-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0008_devuser_groups_devuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='devuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='devuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='devuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='devuser',
            name='user_permissions',
        ),
    ]
