# Generated by Django 4.1.7 on 2023-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0009_alter_devuser_devusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='UserRole',
            field=models.TextField(choices=[('Developer', 'DEV'), ('Senior', 'SEN'), ('Admin', 'ADM')], default='Developer', max_length=12),
        ),
        migrations.AlterField(
            model_name='devuser',
            name='devUserName',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
