# Generated by Django 4.1.7 on 2023-03-22 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0009_alter_ticket_ticketsubmittedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketDateClosed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketDateOpened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
