# Generated by Django 4.1.7 on 2023-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0010_alter_devuser_userrole_alter_devuser_devusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='UserProject',
            field=models.ManyToManyField(blank=True, related_name='userprojects', to='BugTracker.project'),
        ),
    ]
