# Generated by Django 4.1.7 on 2023-03-22 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0010_ticket_ticketdateclosed_ticket_ticketdateopened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketDateOpened',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
