# Generated by Django 4.1.7 on 2023-03-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0012_alter_ticket_ticketdateopened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='TicketDateOpened',
        ),
    ]
