# Generated by Django 4.1.7 on 2023-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0013_remove_ticket_ticketdateopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketDateOpened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
