# Generated by Django 4.1.7 on 2023-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0014_ticket_ticketdateopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketCode',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
