# Generated by Django 4.1.7 on 2023-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0015_ticket_ticketcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='TicketCode',
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketCodeLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
